---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: noderesourcetopologies.k8s.cncf.io
spec:
  group: k8s.cncf.io
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      properties:
        nodes:
          type: array
          items:
            type: object
            properties:
              numaID:
                type: integer
              resources:
                type: object
                additionalProperties:
                  type: string
  names:
    plural: noderesourcetopologies
    singular: noderesourcetopology
    kind: NodeResourceTopology
    shortNames:
      - node-res-topo
