apiVersion: v1
kind: Pod
metadata:
  name: my-scheduler-testpod
spec:
  schedulerName: my-scheduler
  containers:
    - name: testpod
      image: k8s.gcr.io/pause:2.0
      resources:
        limits:
          cpu: 1
          example.com/deviceA: 1
        requests:
          cpu: 1
          example.com/deviceA: 1
